name: 'build-test'
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          valueFile: '__tests__/fixtures/values.yaml'
          propertyPath: 'backend.version'
          value: v1.0.1
          branch: deployment/v1.0.1
          targetBranch: main
          createPR: 'false'
          message: 'Update Image Version to v1.0.1'
          token: ${{ secrets.GH_TOKEN }}

  test-target-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: infrastructure
      - name: Update values.yaml
        uses: ./infrastructure
        with:
          valueFile: '__tests__/fixtures/values.yaml'
          propertyPath: 'backend.version'
          value: v1.2.1
          branch: deployment/v1.2.1
          targetBranch: main
          createPR: 'false'
          message: 'Update Image Version to v1.2.1' 
          workDir: infrastructure
          token: ${{ secrets.GH_TOKEN }}

  test-update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cat Original values.yaml
        run: cat __tests__/fixtures/values.yaml
      - name: Update values.yaml
        uses: ./
        with:
          valueFile: '__tests__/fixtures/values.yaml'
          propertyPath: 'backend.version'
          value: v1.0.1
          commitChange: 'false'
          updateFile: 'true'
      - name: Cat Updated values.yaml
        run: cat __tests__/fixtures/values.yaml
  
  test-multiple-file-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          valueFile: '__tests__/fixtures/values.dev.yaml'
          propertyPath: 'backend.version'
          value: v1.0.1
          branch: deployment/test-multi-file-update
          createPR: 'false'
          message: 'Update DEV Image'
          token: ${{ secrets.GH_TOKEN }}
      - uses: ./
        with:
          valueFile: '__tests__/fixtures/values.stage.yaml'
          propertyPath: 'backend.version'
          value: v1.0.1
          branch: deployment/test-multi-file-update
          createPR: 'false'
          message: 'Update STAGE Image'
          token: ${{ secrets.GH_TOKEN }}
      - uses: ./
        with:
          valueFile: '__tests__/fixtures/values.prod.yaml'
          propertyPath: 'backend.version'
          value: v1.0.1
          branch: deployment/test-multi-file-update
          targetBranch: main
          description: Test GitHub Action
          message: 'Update PROD Image' 
          title: 'Version Update on all Environments'
          token: ${{ secrets.GH_TOKEN }}

  test-value-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          valueFile: '__tests__/fixtures/values.yaml'
          propertyPath: 'config.prod'
          value: "!!bool 'true'"
          branch: deployment/test-bool-value
          targetBranch: main
          description: Test GitHub Action
          message: 'Update Config' 
          title: 'Bool Update on all Environments'
          token: ${{ secrets.GH_TOKEN }}
      - uses: ./
        with:
          valueFile: '__tests__/fixtures/values.yaml'
          propertyPath: 'config.version'
          value: "!!int '1234'"
          branch: deployment/test-int-value
          targetBranch: main
          description: Test GitHub Action
          message: 'Update Config' 
          title: 'Int Update on all Environments'
          token: ${{ secrets.GH_TOKEN }}

  cleanup:
    runs-on: ubuntu-latest
    needs:
      - test-target-repository
      - test-update-file
      - test-multiple-file-changes
      - test-value-types
    steps:
      - uses: actions/checkout@v2
      - name: Delete test branches
        uses: dawidd6/action-delete-branch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          branches: deployment/v1.2.1,deployment/v1.0.1,deployment/test-multi-file-update,deployment/test-bool-value,deployment/test-int-value